In [1]:
import pandas as pd
import datetime

#### Cleaning up February 2021 data for use in Tableau

In [2]:
raw_bike21_df = pd.read_csv("./raw_data/202102-citibike-tripdata.csv")
# raw_bike21_df

In [3]:
# raw_bike21_df.isnull().sum()

In [4]:
# converting day time column from object to datetime type
raw_bike21_df['dt_starttime'] = pd.to_datetime(raw_bike21_df['starttime'])
# raw_bike21_df.head()

In [5]:
#creating columns of only time and date for possible use in Tableau
raw_bike21_df['dt_start_date'] = raw_bike21_df['dt_starttime'].dt.date
raw_bike21_df['dt_starting_time'] = raw_bike21_df['dt_starttime'].dt.time
# raw_bike21_df.head()

In [6]:
# setting dt_starttime as index to allow for filtering using datetime function
index_bike21_df = raw_bike21_df.set_index('dt_starttime')
# index_bike21_df.head(2)

In [7]:
# create new dfs of activity designated ranges for February 2021
am_target_bike21_df = index_bike21_df.between_time('00:00', '06:00')
morn_target_bike21_df = index_bike21_df.between_time('06:01', '12:00')
day_target_bike21_df = index_bike21_df.between_time('12:01', '18:00')
pm_target_bike21_df = index_bike21_df.between_time('18:01', '23:59')

# reset index and then move dt_starttime to end of data set
am_bike21_df = am_target_bike21_df.reset_index()
morn_bike21_df = morn_target_bike21_df.reset_index()
day_bike21_df = day_target_bike21_df.reset_index()
pm_bike21_df = pm_target_bike21_df.reset_index()

# removing (pop) dt_starttime column so it can be replaced at at the end
am_datetime21 = am_bike21_df.pop('dt_starttime')
morn_datetime21 = morn_bike21_df.pop('dt_starttime')
day_datetime21 = day_bike21_df.pop('dt_starttime')
pm_datetime21 = pm_bike21_df.pop('dt_starttime')

#re-inserting column at end of df 
am_bike21_df['dt_starttime'] =  am_datetime21
morn_bike21_df['dt_starttime'] = morn_datetime21
day_bike21_df['dt_starttime'] =  day_datetime21
pm_bike21_df['dt_starttime'] =  pm_datetime21

# pm_bike21_df

#### Cleaning up February 2020 data for use in Tableau

In [8]:
raw_bike20_df = pd.read_csv("./raw_data/202002-citibike-tripdata.csv")
# raw_bike20_df.head(2)

In [9]:
# raw_bike20_df.isnull().sum()

In [10]:
# converting day time column from object to datetime type
raw_bike20_df['dt_starttime'] = pd.to_datetime(raw_bike20_df['starttime'])
# raw_bike20_df.head()

In [11]:
#creating columns of only time and date for possible use in Tableau
raw_bike20_df['dt_start_date'] = raw_bike20_df['dt_starttime'].dt.date
raw_bike20_df['dt_starting_time'] = raw_bike20_df['dt_starttime'].dt.time
# raw_bike20_df.head()

In [12]:
# setting dt_starttime as index to allow for filtering using datetime function
index_bike20_df = raw_bike20_df.set_index('dt_starttime')
# index_bike20_df.head(2)

In [13]:
# create new dfs of activity designated ranges for February 2020
am_target_bike20_df = index_bike20_df.between_time('00:00', '06:00')
morn_target_bike20_df = index_bike20_df.between_time('06:01', '12:00')
day_target_bike20_df = index_bike20_df.between_time('12:01', '18:00')
pm_target_bike20_df = index_bike20_df.between_time('18:01', '23:59')

# reset index and then move dt_starttime to end of data set
am_bike20_df = am_target_bike20_df.reset_index()
morn_bike20_df = morn_target_bike20_df.reset_index()
day_bike20_df = day_target_bike20_df.reset_index()
pm_bike20_df = pm_target_bike20_df.reset_index()

# removing (pop) dt_starttime column so it can be replaced at at the end
am_datetime20 = am_bike20_df.pop('dt_starttime')
morn_datetime20 = morn_bike20_df.pop('dt_starttime')
day_datetime20 = day_bike20_df.pop('dt_starttime')
pm_datetime20 = pm_bike20_df.pop('dt_starttime')

#re-inserting column at end of df 
am_bike20_df['dt_starttime'] =  am_datetime20
morn_bike20_df['dt_starttime'] = morn_datetime20
day_bike20_df['dt_starttime'] =  day_datetime20
pm_bike20_df['dt_starttime'] =  pm_datetime20

pm_bike20_df

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender,dt_start_date,dt_starting_time,dt_starttime
0,1460,2020-02-01 18:01:00.2760,2020-02-01 18:25:21.2350,495,W 47 St & 10 Ave,40.762699,-73.993012,403,E 2 St & 2 Ave,40.725029,-73.990697,33920,Subscriber,1992,1,2020-02-01,18:01:00.276000,2020-02-01 18:01:00.276
1,688,2020-02-01 18:01:00.4730,2020-02-01 18:12:29.2400,459,W 20 St & 11 Ave,40.746745,-74.007756,368,Carmine St & 6 Ave,40.730386,-74.002150,18358,Subscriber,1972,1,2020-02-01,18:01:00.473000,2020-02-01 18:01:00.473
2,541,2020-02-01 18:01:01.6920,2020-02-01 18:10:03.2940,3765,Bushwick Ave & Stagg St,40.709897,-73.940080,3102,Driggs Ave & Lorimer St,40.721791,-73.950415,38394,Subscriber,1990,1,2020-02-01,18:01:01.692000,2020-02-01 18:01:01.692
3,1984,2020-02-01 18:01:02.4240,2020-02-01 18:34:06.9470,448,W 37 St & 10 Ave,40.756604,-73.997901,3372,E 74 St & 1 Ave,40.768974,-73.954823,41316,Subscriber,1947,1,2020-02-01,18:01:02.424000,2020-02-01 18:01:02.424
4,195,2020-02-01 18:01:03.1490,2020-02-01 18:04:18.7490,3093,N 6 St & Bedford Ave,40.717452,-73.958509,3107,Bedford Ave & Nassau Ave,40.723117,-73.952123,32938,Subscriber,1979,1,2020-02-01,18:01:03.149000,2020-02-01 18:01:03.149
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
287750,203,2020-02-29 23:58:43.6800,2020-03-01 00:02:07.5940,3737,Stanton St & Norfolk St,40.720747,-73.986274,317,E 6 St & Avenue B,40.724537,-73.981854,33169,Subscriber,1993,1,2020-02-29,23:58:43.680000,2020-02-29 23:58:43.680
287751,203,2020-02-29 23:58:48.0230,2020-03-01 00:02:11.6640,3737,Stanton St & Norfolk St,40.720747,-73.986274,317,E 6 St & Avenue B,40.724537,-73.981854,39094,Subscriber,1993,2,2020-02-29,23:58:48.023000,2020-02-29 23:58:48.023
287752,357,2020-02-29 23:58:52.5640,2020-03-01 00:04:50.5370,546,E 30 St & Park Ave S,40.744449,-73.983035,3463,E 16 St & Irving Pl,40.735367,-73.987974,40722,Subscriber,1966,2,2020-02-29,23:58:52.564000,2020-02-29 23:58:52.564
287753,169,2020-02-29 23:58:54.5820,2020-03-01 00:01:43.7770,3043,Lewis Ave & Decatur St,40.681460,-73.934903,3052,Lewis Ave & Madison St,40.686312,-73.935775,28696,Subscriber,1994,1,2020-02-29,23:58:54.582000,2020-02-29 23:58:54.582
287754,738,2020-02-29 23:58:58.8110,2020-03-01 00:11:17.7390,3255,8 Ave & W 31 St,40.750585,-73.994685,497,E 17 St & Broadway,40.737050,-73.990093,19975,Subscriber,1999,1,2020-02-29,23:58:58.811000,2020-02-29 23:58:58.811

#### Cleaning up February 2019 data for use in Tableau

In [14]:
raw1_bike19_df = pd.read_csv("./raw_data/201902-citibike-tripdata.csv")
# raw_bike19_df.head()

In [15]:
# raw_bike19_df.isnull().sum()
raw_bike19_df = raw1_bike19_df.dropna()

In [16]:
# converting day time column from object to datetime type
raw_bike19_df['dt_starttime'] = pd.to_datetime(raw_bike19_df['starttime'])
# raw_bike19_df.head()

<ipython-input-16-9748f45de423>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  raw_bike19_df['dt_starttime'] = pd.to_datetime(raw_bike19_df['starttime'])

In [17]:
#creating columns of only time and date for possible use in Tableau
raw_bike19_df['dt_start_date'] = raw_bike19_df['dt_starttime'].dt.date
raw_bike19_df['dt_starting_time'] = raw_bike19_df['dt_starttime'].dt.time
# raw_bike19_df.head()

<ipython-input-17-4a50e2dee318>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  raw_bike19_df['dt_start_date'] = raw_bike19_df['dt_starttime'].dt.date
<ipython-input-17-4a50e2dee318>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  raw_bike19_df['dt_starting_time'] = raw_bike19_df['dt_starttime'].dt.time

In [18]:
# setting dt_starttime as index to allow for filtering using datetime function
index_bike19_df = raw_bike19_df.set_index('dt_starttime')
# index_bike19_df.head(2)

In [19]:
# create new dfs of activity designated ranges for February 2021
am_target_bike19_df = index_bike19_df.between_time('00:00', '06:00')
morn_target_bike19_df = index_bike19_df.between_time('06:01', '12:00')
day_target_bike19_df = index_bike19_df.between_time('12:01', '18:00')
pm_target_bike19_df = index_bike19_df.between_time('18:01', '23:59')

# reset index and then move dt_starttime to end of data set
am_bike19_df = am_target_bike19_df.reset_index()
morn_bike19_df = morn_target_bike19_df.reset_index()
day_bike19_df = day_target_bike19_df.reset_index()
pm_bike19_df = pm_target_bike19_df.reset_index()

# removing (pop) dt_starttime column so it can be replaced at at the end
am_datetime19 = am_bike19_df.pop('dt_starttime')
morn_datetime19 = morn_bike19_df.pop('dt_starttime')
day_datetime19 = day_bike19_df.pop('dt_starttime')
pm_datetime19 = pm_bike19_df.pop('dt_starttime')

#re-inserting column at end of df 
am_bike19_df['dt_starttime'] =  am_datetime19
morn_bike19_df['dt_starttime'] = morn_datetime19
day_bike19_df['dt_starttime'] =  day_datetime19
pm_bike19_df['dt_starttime'] =  pm_datetime19

pm_bike19_df

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender,dt_start_date,dt_starting_time,dt_starttime
0,510,2019-02-01 18:01:00.4020,2019-02-01 18:09:30.7540,3157.0,East End Ave & E 86 St,40.775186,-73.944461,3362.0,Madison Ave & E 82 St,40.778131,-73.960694,17883,Subscriber,1984,1,2019-02-01,18:01:00.402000,2019-02-01 18:01:00.402
1,573,2019-02-01 18:01:14.9280,2019-02-01 18:10:48.6650,446.0,W 24 St & 7 Ave,40.744876,-73.995299,174.0,E 25 St & 1 Ave,40.738177,-73.977387,35472,Subscriber,1988,1,2019-02-01,18:01:14.928000,2019-02-01 18:01:14.928
2,424,2019-02-01 18:01:00.4160,2019-02-01 18:08:04.8130,167.0,E 39 St & 3 Ave,40.748901,-73.976049,492.0,W 33 St & 7 Ave,40.750200,-73.990931,27013,Subscriber,1995,1,2019-02-01,18:01:00.416000,2019-02-01 18:01:00.416
3,540,2019-02-01 18:01:01.6420,2019-02-01 18:10:02.4250,3463.0,E 16 St & Irving Pl,40.735367,-73.987974,3659.0,W 17 St & 9 Ave,40.742949,-74.004137,33391,Subscriber,1957,1,2019-02-01,18:01:01.642000,2019-02-01 18:01:01.642
4,661,2019-02-01 18:01:02.7850,2019-02-01 18:12:04.4810,127.0,Barrow St & Hudson St,40.731724,-74.006744,3258.0,W 27 St & 10 Ave,40.750182,-74.002184,31016,Subscriber,1980,1,2019-02-01,18:01:02.785000,2019-02-01 18:01:02.785
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
226923,962,2019-02-28 23:58:35.2310,2019-03-01 00:14:37.6390,2006.0,Central Park S & 6 Ave,40.765909,-73.976342,3151.0,E 81 St & York Ave,40.772838,-73.949892,21657,Subscriber,1991,1,2019-02-28,23:58:35.231000,2019-02-28 23:58:35.231
226924,984,2019-02-28 23:58:46.0050,2019-03-01 00:15:10.4330,3531.0,Frederick Douglass Blvd & W 129 St,40.812551,-73.949229,3293.0,W 92 St & Broadway,40.792100,-73.973900,18618,Subscriber,1973,1,2019-02-28,23:58:46.005000,2019-02-28 23:58:46.005
226925,819,2019-02-28 23:58:45.1040,2019-03-01 00:12:24.2090,3618.0,27 St & Hunter St,40.748500,-73.941275,3142.0,1 Ave & E 62 St,40.761227,-73.960940,15666,Subscriber,1986,1,2019-02-28,23:58:45.104000,2019-02-28 23:58:45.104
226926,271,2019-02-28 23:58:47.4520,2019-03-01 00:03:19.0490,438.0,St Marks Pl & 1 Ave,40.727791,-73.985649,410.0,Suffolk St & Stanton St,40.720664,-73.985180,20086,Subscriber,1979,1,2019-02-28,23:58:47.452000,2019-02-28 23:58:47.452
226927,569,2019-02-28 23:58:58.9500,2019-03-01 00:08:28.4180,3087.0,Metropolitan Ave & Meeker Ave,40.714133,-73.952344,389.0,Broadway & Berry St,40.710446,-73.965251,32038,Subscriber,1980,1,2019-02-28,23:58:58.950000,2019-02-28 23:58:58.950

#### Writing annual by time periods df to csv

In [20]:
# am_bike21_df.to_csv('am_bike21.csv', index=False)
# morn_bike21_df.to_csv('morn_bike21.csv', index=False)
# day_bike21_df.to_csv('day_bike21.csv', index=False)
# pm_bike21_df.to_csv('pm_bike21.csv', index=False)

# am_bike20_df.to_csv('am_bike20.csv', index=False)
# morn_bike20_df.to_csv('morn_bike20.csv', index=False)
# day_bike20_df.to_csv('day_bike20.csv', index=False)
# pm_bike20_df.to_csv('pm_bike20.csv', index=False)

# am_bike19_df.to_csv('am_bike19.csv', index=False)
# morn_bike19_df.to_csv('morn_bike19.csv', index=False)
# day_bike19_df.to_csv('day_bike19.csv', index=False)
# pm_bike19_df.to_csv('pm_bike19.csv', index=False)

#### Creating 1 file per year

In [21]:
am_temp = [am_bike21_df, am_bike20_df, am_bike19_df]
am_bike_concat_df = pd.concat(am_temp)

morn_temp = [morn_bike21_df, morn_bike20_df, morn_bike19_df]
morn_bike_concat_df = pd.concat(morn_temp)

day_temp = [day_bike21_df, day_bike20_df, day_bike19_df]
day_bike_concat_df = pd.concat(day_temp)

pm_temp = [pm_bike21_df, pm_bike20_df, pm_bike19_df]
pm_bike_concat_df = pd.concat(pm_temp)
pm_bike_concat_df

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender,dt_start_date,dt_starting_time,dt_starttime
0,596,2021-02-03 18:01:01.7970,2021-02-03 18:10:58.1110,3171.0,Amsterdam Ave & W 82 St,40.785247,-73.976673,3350.0,W 100 St & Broadway,40.797372,-73.970412,41481,Subscriber,1984,1,2021-02-03,18:01:01.797000,2021-02-03 18:01:01.797
1,84,2021-02-03 18:01:02.1530,2021-02-03 18:02:27.0030,489.0,10 Ave & W 28 St,40.750664,-74.001768,3735.0,W 30 St & 10 Ave,40.752694,-74.002353,30114,Subscriber,1967,1,2021-02-03,18:01:02.153000,2021-02-03 18:01:02.153
2,1328,2021-02-03 18:01:02.2520,2021-02-03 18:23:10.5640,3699.0,W 50 St & 9 Ave,40.763605,-73.989180,3905.0,4 Ave & E 12 St,40.732647,-73.990110,30853,Subscriber,1985,1,2021-02-03,18:01:02.252000,2021-02-03 18:01:02.252
3,1473,2021-02-03 18:01:04.2410,2021-02-03 18:25:37.4170,3141.0,1 Ave & E 68 St,40.765005,-73.958185,3289.0,W 90 St & Amsterdam Ave,40.790179,-73.972889,38977,Subscriber,1992,2,2021-02-03,18:01:04.241000,2021-02-03 18:01:04.241
4,663,2021-02-03 18:01:10.7910,2021-02-03 18:12:14.2990,530.0,11 Ave & W 59 St,40.771497,-73.990460,519.0,Pershing Square North,40.751873,-73.977706,37540,Customer,1990,1,2021-02-03,18:01:10.791000,2021-02-03 18:01:10.791
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
226923,962,2019-02-28 23:58:35.2310,2019-03-01 00:14:37.6390,2006.0,Central Park S & 6 Ave,40.765909,-73.976342,3151.0,E 81 St & York Ave,40.772838,-73.949892,21657,Subscriber,1991,1,2019-02-28,23:58:35.231000,2019-02-28 23:58:35.231
226924,984,2019-02-28 23:58:46.0050,2019-03-01 00:15:10.4330,3531.0,Frederick Douglass Blvd & W 129 St,40.812551,-73.949229,3293.0,W 92 St & Broadway,40.792100,-73.973900,18618,Subscriber,1973,1,2019-02-28,23:58:46.005000,2019-02-28 23:58:46.005
226925,819,2019-02-28 23:58:45.1040,2019-03-01 00:12:24.2090,3618.0,27 St & Hunter St,40.748500,-73.941275,3142.0,1 Ave & E 62 St,40.761227,-73.960940,15666,Subscriber,1986,1,2019-02-28,23:58:45.104000,2019-02-28 23:58:45.104
226926,271,2019-02-28 23:58:47.4520,2019-03-01 00:03:19.0490,438.0,St Marks Pl & 1 Ave,40.727791,-73.985649,410.0,Suffolk St & Stanton St,40.720664,-73.985180,20086,Subscriber,1979,1,2019-02-28,23:58:47.452000,2019-02-28 23:58:47.452
226927,569,2019-02-28 23:58:58.9500,2019-03-01 00:08:28.4180,3087.0,Metropolitan Ave & Meeker Ave,40.714133,-73.952344,389.0,Broadway & Berry St,40.710446,-73.965251,32038,Subscriber,1980,1,2019-02-28,23:58:58.950000,2019-02-28 23:58:58.950

#### Writing merged df to csv

In [22]:
# am_bike_concat_df.to_csv('am_bike_Feb.csv', index=False)
# morn_bike_concat_df.to_csv('morn_bike_Feb.csv', index=False)
# day_bike_concat_df.to_csv('day_bike_Feb.csv', index=False)
# pm_bike_concat_df.to_csv('pm_bike_Feb.csv', index=False)

#### only used am data because other points were too large (>100 MB).. Data was gathered since code was simple and for possible future use